<a href="https://colab.research.google.com/github/Hayeon101/deep-learning-basic/blob/main/02/02_02_%ED%85%90%EC%84%9C_%EC%A1%B0%EC%9E%91%ED%95%98%EA%B8%B0_(Tensor_Manipulation).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 2. 넘파이로 텐서 만들기 (벡터와 행렬 만들기)

In [ ]:
import numpy as np

#### 1) 1D with Numpy

In [ ]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
# 파이썬으로 설명하면 List를 생성해서 np.array로 1차원 array로 변환함
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


##### 1-1) Numpy 기초 이해하기

In [ ]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [ ]:
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1])

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]


#### 2) 2D with Numpy

In [ ]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [9., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [ 9. 11. 12.]]


In [ ]:
print(t.ndim)
print(t.shape)

2
(4, 3)


## 3. 파이토치 텐서 선언하기 (PyTorch Tensor Allocation)

In [ ]:
import torch

#### 1) 1D with PyTorch

In [ ]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [ ]:
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


#### 2) 2D with PyTorch

In [ ]:
t = torch.FloatTensor([[1., 2., 3.],
                      [4., 5., 6.],
                      [7., 8., 9.],
                      [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [ ]:
print(t[:, 1].size())

torch.Size([4])


In [ ]:
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


#### 3) 브로드캐스팅 (Broadcasting)

딥러닝을 하게 되면 불가피하게 크기가 다른 행렬 또는 텐서에 대해 사칙 연산을 할 필요가 있습니다. 이때 파이토치는 자동으로 크기를 맞춰서 수행하게 해주는 브로드캐스팅 기능을 제공합니다.

In [ ]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [ ]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1+m2)

tensor([[4., 5.]])


In [ ]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

# 브로드캐스팅 과정
# [1, 2]
# ==>  [[1, 2],
#       [1, 2]]
# [3]
# [4]
# ==>  [[3, 3],
#       [4, 4]]

tensor([[4., 5.],
        [5., 6.]])


#### 4) 자주 사용되는 기능들

##### 1) 행렬 곱셈과 곱셈의 차이 (Matrix Multiplication Vs. Multiplication)

In [ ]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shpae of Matrix 2: ', m2.shape)
print(m1.matmul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shpae of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [ ]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shpae of Matrix 2: ', m2.shape)
print(m1 * m2)
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shpae of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


##### 2) 평균 (Mean)

In [ ]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())

tensor(2.5000)


In [ ]:
print(t.mean(dim=0)) # 행 방향 연산 후 첫 번째 차원 (행) 제거

tensor([2., 3.])


In [ ]:
print(t.mean(dim=1)) # 열 방향 연산 후 두 번째 차원 (열) 제거

tensor([1.5000, 3.5000])


In [ ]:
print(t.mean(dim=-1))

tensor([1.5000, 3.5000])


##### 3) 덧셈 (Sum)

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


##### 4) 최대 (Max)와 아그맥스 (ArgMax)

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.max())

tensor(4.)


In [ ]:
print(t.max(dim=0))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [ ]:
print('Max: ', t.max(dim=0)[0])
print('ArgMax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
ArgMax:  tensor([1, 1])


In [ ]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


##### view(), squeeze(), unsqueeze()는 텐서의 원소 수를 유지하면서 모양과 차원을 조절합니다.

##### 5) 뷰 (View) - 원소의 수를 유지하면서 텐서의 크기 변경. 매우 중요!

In [ ]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [ ]:
print(ft.shape)

torch.Size([2, 2, 3])


###### 5-1) 3차원 텐서에서 2차원 텐서로 변경

In [ ]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


###### 5-2) 3차원 텐서의 크기 변경

In [ ]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


##### 6) 스퀴즈 (Squeeze) - 1인 차원을 제거한다.

In [ ]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


##### 7) 언스퀴즈 (Unsqueeze) - 특정 위치에 1인 차원을 추가한다.

In [ ]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [ ]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


##### 8) 타입 캐스팅 (Type Casting)

텐서의 각각의 자료형을 변환하는 것을 타입 캐스팅이라고 합니다.

In [ ]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [ ]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [ ]:
bt = torch.ByteTensor([True,False,False,True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [ ]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


##### 9) 연결하기 (concatenate)

In [ ]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

In [ ]:
print(torch.cat([x,y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [ ]:
print(torch.cat([x,y],dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


##### 10) 스택킹 (Stacking)

In [ ]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [ ]:
print(torch.stack([x,y,z]))

# print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0))
# 같은 역할을 한다.

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [ ]:
print(torch.stack([x,y,z],dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


##### 11) ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서

In [ ]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [ ]:
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


##### 12) In-place Operation (덮어쓰기 연산)

In [ ]:
x = torch.FloatTensor([[1,2],[3,4]])

In [ ]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
